name: Todo Locust Load Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Todo production build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies 
        run: npm ci

      - name: Run Load Test
        uses: luisgerardo05/todo-express@main
        with:
          LOCUSTFILE: "./test/locustfile.py"
          URL:  "http://localhost.com:80"
          USERS: "1"
          RATE: "1"
          RUNTIME: "1m"