name: Todo Locust Load Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Todo production build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.19.0
      - name: Install dependencies 
        run: npm ci

      - name: Run Load Test
        uses: luisgerardo05/todo-express@main
        with:
          LOCUSTFILE: "./test/locustfile.py"
          URL: "http://localhost.com:80"
          USERS: "1"
          RATE: "1"
          RUNTIME: "1m"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/todo-express:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}